services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "4433:4433"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - clinicaltrials-mcp
    restart: unless-stopped
    networks:
      - clinicaltrials-mcp_network

  # New MCP Server Service
  clinicaltrials-mcp:
    container_name: clinicaltrials-mcp
    image: clinicaltrials-mcp:latest
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - clinicaltrials-mcp_network

networks:
  clinicaltrials-mcp_network:
    driver: bridge
